plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lambocheat.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.lambocheat.app.v8'
        minSdk 26
        targetSdk 28
        versionCode 8
        versionName '0.8'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
